version: '2'

services:
 mongo:
    container_name: mongodb_2
    build: 
        context: rpi-mongo
        dockerfile: Dockerfile
    ports:
      - "27017:27017"
    restart: always
 
 shimmer:
    container_name: shimmer
    #image: agileIot/shimmer
    build: 
        context: .
        dockerfile: DockerfileRpi
    ports:
     - "8083:8083"
    environment:
      - MONGO_DB=172.22.0.1
      - AGILE_HOST=$AGILE_HOST
    network_mode: "host" 
    depends_on:
      - mongo   
    restart: always

 shimmer_standalone:
    container_name: shimmer
    build: 
        context: .
        dockerfile: DockerfileRpi
    ports:
     - "8083:8083"
    environment:
      - MONGO_DB=172.22.0.1
      - AGILE_HOST=$AGILE_HOST
    network_mode: "host"
    restart: always 

 shimmer_x86:
    container_name: shimmer
    build: 
        context: .
        dockerfile: Dockerfilex86
    ports:
     - "8083:8083"
    environment:
      - MONGO_DB=172.22.0.1
      - AGILE_HOST=$AGILE_HOST
    network_mode: "host" 
